[package]
name = "orva-events"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
orva-error.workspace = true
orva-data.workspace = true

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true

[dev-dependencies]
